title: "Tech Cottage"
description: "Mojo, Tenmo, Rust, Kubernetes, and systems programming"
author: rbsomeg
baseurl: "/techcottage"
url: "https://ratulb.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
future: true
show_excerpts: true
permalink: /:year/:month/:title/

header_pages:
  - about.md

exclude:
  - AGENTS.md
  - README.md

